apiVersion: v1
kind: Pod
metadata:
  labels:
    app: qeeqbox-chameleon-honeypots-pod
  name: qeeqbox-chameleon-honeypots-pod
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: localhost/default.json
spec:
  restartPolicy: OnFailure
  hostNetwork: false
  containers:
  - name: srv01
    image: localhost/qeeqbox/honeypots
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        add:
        - CAP_NET_ADMIN
        - CAP_NET_RAW
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
      seLinuxOptions:
        type: qeeqbox_chameleon_honeypots.process
    resources:
      requests:
        memory: 2000Mi
        cpu: 1000m
      limits:
        memory: 2000Mi
        cpu: 1000m
    # ports:
    # - containerPort: 3306
    #   hostPort: 3306
    #   hostIP: 0.0.0.0
    #   protocol: tcp
    volumeMounts:
    - mountPath: /app/config.json
      name: honeypots-config
      readOnly: true
    - mountPath: /var/log/honeypots
      name: honeypots-logs
  volumes:
  - name: honeypots-config
    hostPath:
      path: ./configs/config.json
  - name: honeypots-logs
    persistentVolumeClaim:
      claimName: qeeqbox-chameleon-honeypots-logs
